/*
 * Lexer for the "Grammar of the Course" language (CourseGrammar2).
 * Generated by JFlex 1.9.1.
 *
 * Build:  java -jar jflex-full-1.9.1.jar Lexer.flex
 */

%%

%class Lexer
%unicode
%public
%type int
%function nextToken
%line
%column

%{
    public String text  = "";
    public int    intVal = 0;
    public String strVal  = "";

    // 1-based source position of the token most recently returned.
    public int line = 1;
    public int col  = 1;

    private int tok(int t) {
        text = yytext();
        line = yyline + 1;
        col  = yycolumn + 1;
        return t;
    }

    private int ident(int t) {
        text = yytext();
        line = yyline + 1;
        col  = yycolumn + 1;
        return t;
    }

    private String unescape(String s) {
        StringBuilder b = new StringBuilder();
        for (int i = 0; i < s.length(); i++) {
            char c = s.charAt(i);
            if (c == '\\' && i + 1 < s.length()) {
                char n = s.charAt(++i);
                switch (n) {
                    case 'n':  b.append('\n'); break;
                    case 't':  b.append('\t'); break;
                    case 'r':  b.append('\r'); break;
                    case '"':  b.append('"');  break;
                    case '\\': b.append('\\'); break;
                    default:   b.append(n);    break;
                }
            } else {
                b.append(c);
            }
        }
        return b.toString();
    }
%}

%eofval{
    return Toks.EOF;
%eofval}

LineTerminator = \r|\n|\r\n
WhiteSpace     = {LineTerminator} | [ \t\f]
Digit          = [0-9]
Letter         = [a-zA-Z_]
Identifier     = {Letter}({Letter}|{Digit})*
StringLiteral  = \"([^\"\\]|\\.)*\"

%%

<YYINITIAL> {
    {WhiteSpace}     { /* ignore whitespace */ }

    "if"             { return tok(Toks.IF); }
    "then"           { return tok(Toks.THEN); }
    "else"           { return tok(Toks.ELSE); }
    "end"            { return tok(Toks.END); }
    "repeat"         { return tok(Toks.REPEAT); }
    "until"          { return tok(Toks.UNTIL); }
    "loop"           { return tok(Toks.LOOP); }
    "exit"           { return tok(Toks.EXIT); }
    "put"            { return tok(Toks.PUT); }
    "get"            { return tok(Toks.GET); }
    "var"            { return tok(Toks.VAR); }
    "func"           { return tok(Toks.FUNC); }
    "proc"           { return tok(Toks.PROC); }
    "integer"        { return tok(Toks.INTEGER); }
    "boolean"        { return tok(Toks.BOOLEAN); }
    "true"           { return tok(Toks.TRUE); }
    "false"          { return tok(Toks.FALSE); }
    "skip"           { return tok(Toks.SKIP); }

    {Identifier}     { return ident(Toks.IDENT); }
    {Digit}+         {
                        text = yytext();
                        line = yyline + 1;
                        col  = yycolumn + 1;
                        try {
                            intVal = Integer.parseInt(yytext());
                        } catch (NumberFormatException e) {
                            throw new RuntimeException("(" + (yyline + 1) + ":" + (yycolumn + 1)
                                    + ") integer literal out of range: " + yytext());
                        }
                        return Toks.INT;
                     }
    {StringLiteral}  {
                        text = yytext();
                        line = yyline + 1;
                        col  = yycolumn + 1;
                        String s = yytext();
                        s = s.substring(1, s.length() - 1);
                        strVal = unescape(s);
                        return Toks.STRING;
                     }

    ":="             { return tok(Toks.ASSIGN); }
    "<="             { return tok(Toks.LE); }
    ">="             { return tok(Toks.GE); }
    "="              { return tok(Toks.EQ); }
    "#"              { return tok(Toks.NE); }
    "<"              { return tok(Toks.LT); }
    ">"              { return tok(Toks.GT); }
    "("              { return tok(Toks.LPAREN); }
    ")"              { return tok(Toks.RPAREN); }
    "["              { return tok(Toks.LBRACKET); }
    "]"              { return tok(Toks.RBRACKET); }
    "{"              { return tok(Toks.LBRACE); }
    "}"              { return tok(Toks.RBRACE); }
    ";"              { return tok(Toks.SEMI); }
    ":"              { return tok(Toks.COLON); }
    ","              { return tok(Toks.COMMA); }
    "+"              { return tok(Toks.PLUS); }
    "-"              { return tok(Toks.MINUS); }
    "*"              { return tok(Toks.STAR); }
    "/"              { return tok(Toks.SLASH); }
    "&"              { return tok(Toks.AMP); }
    "|"              { return tok(Toks.PIPE); }
    "~"              { return tok(Toks.TILDE); }

    [^]              { throw new RuntimeException("(" + (yyline + 1) + ":" + (yycolumn + 1)
                            + ") illegal character: '" + yytext() + "'"); }
}
